name: Auto Fetch FIFA Data

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      # Di-upgrade ke v4 biar GitHub gak rewel
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Di-upgrade ke v5 biar support Node terupdate
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Cloudscraper
        run: pip install cloudscraper

      - name: Tembak API Pakai Python (Bypass Cloudflare)
        run: |
          python -c "
          import cloudscraper
          scraper = cloudscraper.create_scraper()
          
          # Tembak Matches
          print('Sedot data jadwal...')
          m = scraper.get('https://worldcupjson.net/matches?by_date=asc')
          with open('matches.json', 'w') as f: f.write(m.text)
          
          # Tembak Standings
          print('Sedot data klasemen...')
          s = scraper.get('https://worldcupjson.net/teams/group_results')
          with open('standings.json', 'w') as f: f.write(s.text)
          "

      - name: Commit & Push Data
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "FIFA Scraper Bot"
          git add matches.json standings.json
          git commit -m "Auto update skor via Python" || exit 0
          git push
